site_name: Memorix AI
site_description: AI Memory Management Framework
site_author: Memorix AI Team
site_url: https://memorix-ai.github.io/memorix-docs/

# Repository
repo_name: memorix-ai/memorix-docs
repo_url: https://github.com/memorix-ai/memorix-docs
edit_uri: edit/main/docs/

# Theme
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Installation: install.md
    - Quick Start: quickstart.md
  - User Guide:
    - Basic Usage: usage/basic.md
    - Memory Management: usage/memory.md
    - Vector Stores: usage/vectorstores.md
    - Embedding Models: usage/embeddings.md
  - API Reference:
    - Memory API: api/memory_api.md
    - Vector Store: api/vector_store.md
    - Embedder: api/embedder.md
    - Configuration: api/config.md
  - Examples:
    - Basic Examples: examples/basic.md
    - Chatbot Memory: examples/chatbot.md
    - Knowledge Base: examples/knowledge_base.md
  - Development:
    - Contributing: contributing.md
    - CI/CD and Deployment: contributing/ci-cd.md
    - Architecture: architecture.md
    - Changelog: changelog.md

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

# Markdown extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_generator: !!python/object/apply:pymdownx.emoji.to_svg
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

# Extra CSS and JS
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Extra files to include
extra:
  logo: img/MEMORIX-AI.png

# Copyright
copyright: Copyright &copy; 2024 Memorix AI 