name: Setup GitHub Pages

on:
  workflow_run:
    workflows: ["Deploy Documentation"]
    types:
      - completed

permissions:
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  setup-pages:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: mkdocs 